<?php
const FIELD_ID_JOB=0;
const FIELD_PCS_PER_TRAY=7;
const FIELD_OPERATION=12;
const FIELD_FIRST_OP=13;
const FIELD_OP_DESCRIPTION=14;
const FIELD_QTY_ORDER=17;
const FIELD_QTY_COMP=18;
const FIELD_QTY_OPEN=19;
?>